### ISSUE TITLE
Wrong confirmation link in email

### ISSUE THREAD

**Issue by alQlagin** [HipsterCreative/yii2-user-mongo#1]
You have a mistake when you generate confirmation mail. Method User::getConfirmationUrl uses $this->_id as id route param. You should use (string) $this->_id instead. 
Here $this->_id is MongoID object need to be converted into string

**Comment by lhilton** [comment]
Thank you for the find, I'll get an update pushed this morning as soon as I get this coffee finished.

In case I wasn't clear enough in the readme, this is a very initial effort at the conversion. We still haven't finished going through the majority of the features, and we definitely aren't at anything I would consider stable yet.

If you find anything else, I would appreciate the assistance.

**Comment by lhilton** [comment]
This is patched now. There is still an outstanding issue in the password reset form that needs resolving, I'll hold this ticket open until that is fixed.

**Comment by lhilton** [comment]
I have fixed the password reset process as well, closing the issue.
